version: "3"
services:
    mysql_db:
        image: 'mysql:latest'
        container_name: astral_mysql
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        volumes:
          - './data_mysql:/var/lib/mysql'
          - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: shop
          MYSQL_USER: user
          MYSQL_PASSWORD: user1234  
        expose:
          - '3306'
    nginx: 
        restart: always
        build:
            context: .
            dockerfile: ./AstralFrontend/Dockerfile
        container_name: astral_nginx        
        ports:
            - 80:80
        volumes:
            - ./AstralFrontend/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - backend
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./AstralBackend/Dockerfile
        container_name: astral_backend
        expose:
            - 8080   
        depends_on:
            - mysql_db    